export const HIDE_DRAWER_MERGIN_LEFT = 0;
export const COLLAPSED_MERGIN_LEFT = 80;
export const NON_COLLAPSED_MERGIN_LEFT = 250;
export const HORIZONTAL_SPACING = 20;
export const VERTICAL_SPACING = 20;
export const GUTTER_SPACING = [HORIZONTAL_SPACING, VERTICAL_SPACING];
export const COLLAPSED_MARGIN_RIGHT = 100;
export const NON_COLLPASED_MARGIN_RIGHT = 270;
